### ISSUE TITLE
Doesn't seem to work for variables with numbers

### ISSUE THREAD

**Issue by nathankot** [pbrisbin/load-env#1]
e.g `S3_KEY` is being ignored

**Comment by pbrisbin** [comment]
Thanks for the report. The limitation is [here](https://github.com/pbrisbin/load-env/blob/master/src/LoadEnv/Parse.hs#L50) and probable just needs `<|> number`. As part of fixing this I'll try to find out the OS limitations on environment variable names and ensure we allow and enforce that.

**Comment by nathankot** [comment]
@pbrisbin awesome thanks =D
