### ISSUE TITLE
Error with parsing lower case variable names

### ISSUE THREAD

**Issue by denibertovic** [pbrisbin/load-env#3]
I have variable names in the format of "export TF_VAR_foo=foobar" and they are being ignored  by the parser.

I believe the issue is here:

```
identifier :: Parser String
identifier = do
    x <- upper <|> underscore
    ys <- many $ upper <|> digit <|> underscore

    pure (x:ys)

  where
    underscore = char '_'
```

To reproduce you can run this in ghci:

```
λ: parse parseEnvironment "" "export TF_VAR_foo=foo\n"
Right []
```

**Comment by pbrisbin** [comment]
Hey there- this is because the library, at least at this time, is attempting to comply with the specification for envirionment variables:

https://github.com/pbrisbin/load-env/blob/master/src/LoadEnv/Parse.hs#L40-L46

```
-- Environment variable names used by the utilities in the Shell and Utilities
-- volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits,
-- and the '_' (underscore) from the characters defined in Portable Character
-- Set and do not begin with a digit.
--
-- <http://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap08.html>
--
```

In this specification, lower-case letters are not allowed.

I could be convinced to be more lax here, but we'd need to decide how lax -- should we allow variables _starting_ with a lower-case, for example?

**Comment by denibertovic** [comment]
@pbrisbin I'm running into this issue with terraform environment variables: https://www.terraform.io/docs/configuration/environment-variables.html#tf_var_name

I've seen this pattern used in some other tools as well. 

Regarding the spec, there appears to be a newer edition here: http://pubs.opengroup.org/onlinepubs/9699919799/

It says:

> Environment variable names used by the utilities in the Shell and Utilities volume of POSIX.1-2017 consist solely of uppercase letters, digits, and the <underscore> ( '_' ) from the characters defined in Portable Character Set and do not begin with a digit. Other characters may be permitted by an implementation; applications shall tolerate the presence of such names. Uppercase and lowercase letters shall retain their unique identities and shall not be folded together. The name space of environment variable names containing lowercase letters is reserved for applications. Applications can define any environment variables with names from this name space without modifying the behavior of the standard utilities. 

If I'm reading this correctly we should allow all lower case as well as mixed. The only rule is that it can't start with a digit. What do you think? Am I reading this right?

**Comment by denibertovic** [comment]
BTW I can come up with a PR if we agree on the implementation (if you want)...though probably not today.

**Comment by pbrisbin** [comment]
Oh nice, that sounds great. Yeah, if you could implement it (and be sure to update the comment), I'd happily merge and release. Implementing should be pretty easy, just tossing `<|> lowercase` wherever the `uppercase` parsing is being used, I think.
