### ISSUE TITLE
Don't overwrite an existing variable

### ISSUE THREAD

**Issue by pbrisbin** [pbrisbin/load-env#5]
If a variable is already in the environment, the one read by load-env will overwrite it in our process. One could prefer either way, but I'm thinking leaving it alone is a more useful default. Maybe some kind of force option to set anyway?

**Comment by pbrisbin** [comment]
Decided to just change how we work and never overwrite. Closed in a239a30ed41c30cb49903d817cb4e52b0f499900.

If anyone prefers the old ovewrite behavior, we can create a new function for it.

**Comment by alextes** [comment]
Thanks, was coming here to ask about this. I'll update 👍 .
