### ISSUE TITLE
Comparison to stackbuilders/dotenv-hs

### ISSUE THREAD

**Issue by nsaunders** [pbrisbin/load-env#9]
[stackbuilders/dotenv-hs](http://github.com/stackbuilders/dotenv-hs) is another Haskell Dotenv port. It might be good to compare existing or planned features in the README to help people decide which one to use.

**Comment by pbrisbin** [comment]
Thanks for the heads-up. I didn't know about that; I don't think it existed when I wrote this one ages ago... At first glance, it's _way_ more feature-ful than this one. If that's good or bad, I leave up to you -- but my library is doing almost nothing compared to everything it does. I'll try to get a note about this into our README.

**Comment by pbrisbin** [comment]
I'm archiving this repo and directing users to dotenv-hs.
